### PR TITLE
Added missing branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by SpacePossum** [comment]
thank you @GrahamCampbell !

sorry for the delay, I'm/was out for a few weeks without internet and/or laptop :)

**Comment by GrahamCampbell** [comment]
No problem. :)

**Comment by SpacePossum** [comment]
@GrahamCampbell 
When I'm going to release 3.0, I should update the alias to 4-dev in master. 
But I'm wondering, what should the alias be in `composer.json` within the 3.0 release branch itself, would it even matter?

**Comment by GrahamCampbell** [comment]
The branch alias should reflect the next release on the mast branch itself. It doesn't matter what is in the branch on tagging, it is only used by packagist, and packagist only looks at the current head of each branch, so any historical branch alias errors don't matter.

Would be fine to leave the master as 3.0-dev until any breaking changes are made, and then it should be 4.0-dev, and if new features come in, then it should be 3.1-dev. :)

**Comment by SpacePossum** [comment]
ah thanks for the insights man :)
I know how to proceed now :+1:

**Comment by GrahamCampbell** [comment]
🚀

**Comment by SpacePossum** [comment]
3.0 is out :)

**Pull request merged**
