### PR TITLE
Add PHPUnit 7.0 conflict

### PR DESCRIPTION
**Pull request by Slamdunk**
Fatal error: Declaration of GeckoPackages\PHPUnit\Constraints\SameStringsConstraint::additionalFailureDescription($other) must be compatible with PHPUnit\Framework\Constraint\Constraint::additionalFailureDescription($other): string in ./vendor/gecko-packages/gecko-php-unit/src/PHPUnit/Constraints/SameStringsConstraint.php on line 43

### CODE REVIEW

**Comment by SpacePossum** [comment]
thank you @Slamdunk

**Comment by Slamdunk** [comment]
May I ask you if you are going to build a bugfix release for this?

**Comment by SpacePossum** [comment]
:+1: 
I've released v3.1.1 with your fix.

**Comment by Slamdunk** [comment]
Thank you

**Comment by Slamdunk** [comment]
For your interest: this patch was needed, but a bit useless because Composer dependency tree resolution installs v3.0.0 or v3.1.0 which don't provide this conflict.
Don't know if it can be solved in any method different from overriding already released tags 😦

**Comment by SpacePossum** [comment]
lets see why composer doesn't up to 3.1, IIRC there not much of a reason not to update to 3.1

**Comment by ndench** [comment]
Is there any reason why this limit allow up to but not version `7.0` of phpunit?:
```
        "phpunit/phpunit": "<6.0 || >=7.0"
```

There are a handful of [phpunit releases](https://github.com/sebastianbergmann/phpunit/releases) above version `6.5` but lower than `7.0`.

**Comment by Slamdunk** [comment]
Omg, I'm sorry, I thought `>6.5` meant `>=6.0.0`, I don't have my pc now, we need a bugfix soon :(

**Pull request merged**
